### ISSUE TITLE
Bug : Profiles showing as "Inactive" and no controls are shown in the dashboard.

### ISSUE THREAD

**Issue by rams3sh** [OpenCSPM/opencspm#12] opened 2020-11-14 07:02 UTC
I followed the process as mentioned in the video and have been tracking docker-compose logs and all to check if there has been any error. 
However , the logs were clear.

Once everything is loaded. I do get the profiles listed in the profiles page with status being `inactive`. 

No controls are showing on the dashboard. 

Image below :- 
![image](https://user-images.githubusercontent.com/5143597/99141804-d36b0480-2674-11eb-83b1-31081f0981a9.png)

I have loaded the community and enterprise controls both as suggested in the video. 

My directory structure below for reference. 
```
├── opencspm
│   ├── assets
│   ├── collection
│   ├── config
│   ├── docker
│   ├── load_dir
│   ├── site
│   └── terraform
└── opencspm-controls
    ├── opencspm-darkbit-community-controls
    └── opencspm-darkbit-enterprise-controls
```

**Comment by joshlarsen** [comment] 2020-11-14 11:49
@rams3sh, it looks like the controls did not actually load for some reason. You should see a number of logs from the `worker` container that look like this:

```
...
worker_1  | Control: opencspm-darkbit-community-controls - darkbit-aws-20
worker_1  | Control: opencspm-darkbit-community-controls - darkbit-aws-23
worker_1  | Control: opencspm-darkbit-community-controls - darkbit-aws-29
worker_1  | Control: opencspm-darkbit-community-controls - darkbit-aws-31
worker_1  | Control: opencspm-darkbit-community-controls - darkbit-aws-32
worker_1  | Control: opencspm-darkbit-community-controls - darkbit-aws-34
worker_1  | Control: opencspm-darkbit-community-controls - darkbit-aws-35
worker_1  | Control: opencspm-darkbit-community-controls - darkbit-aws-42
...
```

Also check that the controls volumes is mapped into the `core` container:

```
$ docker-compose exec core ls -lR controls

controls:
total 0
drwxr-xr-x 9 app app 288 Nov 14 11:31 opencspm-darkbit-community-controls
drwxr-xr-x 6 app app 192 Nov 14 11:31 opencspm-darkbit-enterprise-controls

controls/opencspm-darkbit-community-controls:
total 236
-rw-r--r-- 1 app app   1069 Nov 14 11:31 LICENSE
-rw-r--r-- 1 app app   1306 Nov 14 11:31 README.md
-rw-r--r-- 1 app app 169807 Nov 14 11:31 config.yaml
-rw-r--r-- 1 app app  59453 Nov 14 11:31 controls_spec.rb

controls/opencspm-darkbit-enterprise-controls:
total 356
-rw-r--r-- 1 app app   1069 Nov 14 11:31 LICENSE
-rw-r--r-- 1 app app   1047 Nov 14 11:31 README.md
-rw-r--r-- 1 app app 355849 Nov 14 11:31 config.yaml
```

**Comment by rams3sh** [comment] 2020-11-14 14:18
Yeah . I didnt get the log entries as shown in your comment.

The below is the output of the command you had mentioned :- 
```
demo@demo:~/Experiments/opencspm/opencspm/docker$ docker-compose exec core ls -lR controls
controls:
total 8
drwxrwxr-x 3 1000 1000 4096 Nov 13 20:54 opencspm-darkbit-community-controls
drwxrwxr-x 3 1000 1000 4096 Nov 13 20:55 opencspm-darkbit-enterprise-controls

controls/opencspm-darkbit-community-controls:
total 236
-rw-rw-r-- 1 1000 1000   1069 Nov 13 20:54 LICENSE
-rw-rw-r-- 1 1000 1000   1306 Nov 13 20:54 README.md
-rw-rw-r-- 1 1000 1000 169807 Nov 13 20:54 config.yaml
-rw-rw-r-- 1 1000 1000  59453 Nov 13 20:54 controls_spec.rb

controls/opencspm-darkbit-enterprise-controls:
total 356
-rw-rw-r-- 1 1000 1000   1069 Nov 13 20:55 LICENSE
-rw-rw-r-- 1 1000 1000   1047 Nov 13 20:55 README.md
-rw-rw-r-- 1 1000 1000 355849 Nov 13 20:55 config.yaml
```

I have also attached the logs of docker-compose , if that helps. 


While loading it does not give any permission errors, however once I click on data reload in the web ui, it does show some permission error as shown in the log. 

Also its not just the controls , demo data also has problem in loading.
```
demo@demo:~/Experiments/opencspm/opencspm/docker$  docker-compose exec core ls -lR data
data:
total 4
drwxrwxr-x 5 1000 1000 4096 Nov 13 20:56 demo

data/demo:
total 12
drwxrwxr-x 2 1000 1000 4096 Nov 13 20:56 aws
drwxrwxr-x 2 1000 1000 4096 Nov 13 20:56 gcp
drwxrwxr-x 2 1000 1000 4096 Nov 13 20:56 gcp-iam

data/demo/aws:
total 12
-rw-rw-r-- 1 1000 1000 4345 Nov 13 20:56 aws_recon_sample.json
-rw-rw-r-- 1 1000 1000   22 Nov 13 20:56 manifest.txt

data/demo/gcp:
total 944
-rw-rw-r-- 1 1000 1000   4832 Nov 13 20:56 1590603998-iam-policy.json
-rw-rw-r-- 1 1000 1000 951285 Nov 13 20:56 1590603998-resource.json
-rw-rw-r-- 1 1000 1000     52 Nov 13 20:56 manifest.txt

data/demo/gcp-iam:
total 820
-rw-rw-r-- 1 1000 1000 834099 Nov 13 20:56 full-iam-permissions.json
-rw-rw-r-- 1 1000 1000     26 Nov 13 20:56 manifest.txt

```

[docker-compose_log.txt](https://github.com/OpenCSPM/opencspm/files/5540876/docker-compose_log.txt)

**Comment by joshlarsen** [comment] 2020-11-14 15:13
Can you please run:

```
docker-compose exec core bundle exec rails db:seed
```

This should generate activity on the `worker` container.

**Comment by rams3sh** [comment] 2020-11-14 15:36
Thanks , that loads the controls up !!

![image](https://user-images.githubusercontent.com/5143597/99150817-29639a80-26bd-11eb-9204-c0a84de63ca8.png)


But the data still doesnt get loaded. Sample snippet below.

```
worker_1  | I, [2020-11-14T15:33:15.175861 #1]  INFO -- : [ActiveJob] [RunnerJob] [80ad77be-160a-4a13-8122-0f895d308a96] Loading data
worker_1  | Loading config file: load_config/config.yaml
worker_1  | Fetching files from remote buckets and local directories
worker_1  | Cleaning /app/load_dir
worker_1  | /app/data/demo
worker_1  | Copying from /app/data/demo/aws/aws_recon_sample.json to /app/load_dir/tmp-afftcCpO-aws_recon_sample.json
worker_1  | #<Errno::EACCES: Permission denied @ rb_sysopen - /app/load_dir/tmp-afftcCpO-aws_recon_sample.json>
worker_1  | Copying from /app/data/demo/gcp-iam/full-iam-permissions.json to /app/load_dir/tmp-tNYUAutw-full-iam-permissions.json
worker_1  | #<Errno::EACCES: Permission denied @ rb_sysopen - /app/load_dir/tmp-tNYUAutw-full-iam-permissions.json>
worker_1  | Copying from /app/data/demo/gcp/1590603998-iam-policy.json to /app/load_dir/tmp-ZhzPQhrw-1590603998-iam-policy.json
worker_1  | #<Errno::EACCES: Permission denied @ rb_sysopen - /app/load_dir/tmp-ZhzPQhrw-1590603998-iam-policy.json>
worker_1  | Enriching data
```

**Comment by joshlarsen** [comment] 2020-11-14 15:52
Can you paste the output of:

```
docker-compose exec core ls -l
```

and

```
docker-compose exec core ls -l load_dir
```

**Comment by rams3sh** [comment] 2020-11-14 16:04
```
demo@demo:~/Experiments/opencspm/opencspm/docker$ docker-compose exec core ls -l
total 84
-rw-r--r-- 1 app  app  1234 Nov  6 15:17 Gemfile
-rw-r--r-- 1 app  app  9994 Nov 13 16:54 Gemfile.lock
-rw-r--r-- 1 app  app   227 Oct 15 13:32 Rakefile
drwxr-xr-x 9 app  app  4096 Nov 14 05:07 app
drwxr-xr-x 2 app  app  4096 Nov 14 05:07 bin
drwxr-xr-x 5 app  app  4096 Nov 14 05:07 config
-rw-r--r-- 1 app  app   130 Oct 15 13:32 config.ru
drwxrwxr-x 4 1000 1000 4096 Nov 13 20:55 controls
drwxrwxr-x 3 1000 1000 4096 Nov 13 20:56 data
drwxr-xr-x 3 app  app  4096 Nov 14 05:07 db
-rwxr-xr-x 1 app  app   470 Nov 13 16:52 init.sh
drwxr-xr-x 4 app  app  4096 Nov 14 05:07 lib
drwxrwxr-x 2 1000 1000 4096 Nov 14 06:45 load_config
drwxr-xr-x 2 1000 1000 4096 Nov 14 05:07 load_dir
drwxr-xr-x 2 app  app  4096 Nov 14 07:00 log
drwxr-xr-x 5 app  app  4096 Nov 14 05:07 public
drwxr-xr-x 8 app  app  4096 Nov 14 05:07 spec
drwxr-xr-x 8 app  app  4096 Nov 14 05:07 test
drwxr-xr-x 5 app  app  4096 Nov 14 05:07 tmp


demo@demo:~/Experiments/opencspm/opencspm/docker$ docker-compose exec core ls -l load_dir
total 0

```

**Comment by rams3sh** [comment] 2020-11-14 16:20
Tried to perform copy file through the shell of the core container .
Details below :-
```
app@core:~$ whoami
app
app@core:~$ cp /app/data/demo/aws/aws_recon_sample.json /app/load_dir/
cp: cannot create regular file '/app/load_dir/aws_recon_sample.json': Permission denied
app@core:~$ ls -l /app/
total 84
-rw-r--r-- 1 app  app  1234 Nov  6 15:17 Gemfile
-rw-r--r-- 1 app  app  9994 Nov 13 16:54 Gemfile.lock
-rw-r--r-- 1 app  app   227 Oct 15 13:32 Rakefile
drwxr-xr-x 9 app  app  4096 Nov 14 05:07 app
drwxr-xr-x 2 app  app  4096 Nov 14 05:07 bin
drwxr-xr-x 5 app  app  4096 Nov 14 05:07 config
-rw-r--r-- 1 app  app   130 Oct 15 13:32 config.ru
drwxrwxr-x 4 1000 1000 4096 Nov 13 20:55 controls
drwxrwxr-x 3 1000 1000 4096 Nov 13 20:56 data
drwxr-xr-x 3 app  app  4096 Nov 14 05:07 db
-rwxr-xr-x 1 app  app   470 Nov 13 16:52 init.sh
drwxr-xr-x 4 app  app  4096 Nov 14 05:07 lib
drwxrwxr-x 2 1000 1000 4096 Nov 14 06:45 load_config
drwxr-xr-x 2 1000 1000 4096 Nov 14 05:07 load_dir
drwxr-xr-x 2 app  app  4096 Nov 14 07:00 log
drwxr-xr-x 5 app  app  4096 Nov 14 05:07 public
drwxr-xr-x 8 app  app  4096 Nov 14 05:07 spec
drwxr-xr-x 8 app  app  4096 Nov 14 05:07 test
drwxr-xr-x 5 app  app  4096 Nov 14 05:07 tmp
app@core:~$ 
```
Seems like there is a permission issue for the user `app` on the load_dir folders and others marked with `1000` as owning user and group

**Comment by joshlarsen** [comment] 2020-11-14 16:27
Yeah, not sure why those directories are owned by uid 1000. They should be owned by `app`.

Can you try to bring it all down and back up clean?

```
docker-compose down -v
```

then

```
docker-compose up
```

**Comment by rams3sh** [comment] 2020-11-14 16:59
Same state . No chage
```
docker-compose exec core /bin/bash
app@core:~$ ls -l
total 84
-rw-r--r-- 1 app  app  1234 Nov  6 15:17 Gemfile
-rw-r--r-- 1 app  app  9994 Nov 13 16:54 Gemfile.lock
-rw-r--r-- 1 app  app   227 Oct 15 13:32 Rakefile
drwxr-xr-x 9 app  app  4096 Nov 14 16:55 app
drwxr-xr-x 2 app  app  4096 Nov 14 16:55 bin
drwxr-xr-x 5 app  app  4096 Nov 14 16:55 config
-rw-r--r-- 1 app  app   130 Oct 15 13:32 config.ru
drwxrwxr-x 4 1000 1000 4096 Nov 13 20:55 controls
drwxrwxr-x 3 1000 1000 4096 Nov 13 20:56 data
drwxr-xr-x 3 app  app  4096 Nov 14 16:55 db
-rwxr-xr-x 1 app  app   470 Nov 13 16:52 init.sh
drwxr-xr-x 4 app  app  4096 Nov 14 16:55 lib
drwxrwxr-x 2 1000 1000 4096 Nov 14 06:45 load_config
drwxr-xr-x 2 1000 1000 4096 Nov 14 05:07 load_dir
drwxr-xr-x 2 app  app  4096 Nov 13 16:22 log
drwxr-xr-x 5 app  app  4096 Nov 14 16:55 public
drwxr-xr-x 8 app  app  4096 Nov 14 16:55 spec
drwxr-xr-x 8 app  app  4096 Nov 14 16:55 test
drwxr-xr-x 5 app  app  4096 Nov 14 16:55 tmp
app@core:~$ cp /app/data/demo/aws/aws_recon_sample.json /app/load_dir/
cp: cannot create regular file '/app/load_dir/aws_recon_sample.json': Permission denied
```

**Comment by joshlarsen** [comment] 2020-11-14 17:11
Not sure what is going on there. Maybe something with your host volume permissions.

You could try to exec into the container as root and change the ownership of that directory. That won't fix it long term, but may help get it working in the interim.

```
$ docker exec -ti -u root <container-id> bash

root@core:/app# chown -R app:app load_dir
root@core:/app# 
```

**Comment by joshlarsen** [comment] 2020-11-14 17:46
Ah, I see what the problem is. We don't mount `load_dir` from the host anymore. That should have been updated in `docker-compose.yml`.

Please pull the latest to get the new `docker-compose.yml`.

**Comment by joshlarsen** [comment] 2020-11-16 14:24
@rams3sh please re-open if this is not resolved.

**Closed by joshlarsen** 2020-11-16 14:24 UTC
Labels: bug, core
